from __future__ import annotations

NAVIGATION_TARGETS = [
    {
        'key': 'ai',
        'href': '/ai',
        'label': 'AI Assistant',
        'description': 'AI assistant landing page.',
        'keywords': ['assistant', 'chat', 'copilot'],
    },
    {
        'key': 'ai_approvals',
        'href': '/ai/approvals',
        'label': 'AI Approvals',
        'description': 'Review pending AI approvals.',
        'keywords': ['approval', 'approvals'],
    },
    {
        'key': 'ai_history',
        'href': '/ai/history',
        'label': 'AI History',
        'description': 'See completed AI actions and outcomes.',
        'keywords': ['history', 'activity'],
    },
    {
        'key': 'purchase_orders',
        'href': '/orders/purchase',
        'label': 'Purchase Orders',
        'description': 'Purchase order list and status workspace.',
        'keywords': ['po', 'purchase order', 'procurement'],
    },
    {
        'key': 'purchase_orders_new',
        'href': '/orders/purchase/new',
        'label': 'New Purchase Order',
        'description': 'Create a new purchase order draft.',
        'keywords': ['create po', 'new po', 'draft po'],
    },
    {
        'key': 'products',
        'href': '/products',
        'label': 'Products',
        'description': 'Browse and manage the product catalog.',
        'keywords': ['catalog', 'product'],
    },
    {
        'key': 'products_new',
        'href': '/products/new',
        'label': 'New Product',
        'description': 'Create a new product with variants and sizes.',
        'keywords': ['create product', 'new product'],
    },
    {
        'key': 'inventory_stock',
        'href': '/inventory/stock-on-hand',
        'label': 'Stock On Hand',
        'description': 'Current stock balances by SKU and location.',
        'keywords': ['stock', 'on hand', 'inventory'],
    },
    {
        'key': 'inventory_movements',
        'href': '/inventory/movements',
        'label': 'Inventory Movements',
        'description': 'Movement history across all inventory transactions.',
        'keywords': ['movement', 'movements', 'history'],
    },
    {
        'key': 'inventory_receipts',
        'href': '/inventory/receipts',
        'label': 'Receipts',
        'description': 'Stock receipts and received purchase orders.',
        'keywords': ['receive stock', 'receipts'],
    },
    {
        'key': 'master_suppliers',
        'href': '/master/suppliers',
        'label': 'Suppliers',
        'description': 'Manage supplier master data.',
        'keywords': ['supplier', 'vendors'],
    },
    {
        'key': 'master_locations',
        'href': '/master/locations',
        'label': 'Locations',
        'description': 'Manage warehouse and store locations.',
        'keywords': ['warehouse', 'location', 'store'],
    },
    {
        'key': 'audit',
        'href': '/audit',
        'label': 'Audit',
        'description': 'Operational audit log.',
        'keywords': ['audit', 'logs'],
    },
]
